repository: BYR-Navi/BYR-Navi
repository_url: https://github.com/BYR-Navi/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: 学霸哥的宝藏导航
alias_en: xuebage
alias_cn: 学霸哥的宝藏导航
description: 学霸哥的宝藏导航
keywords: 学霸哥的宝藏导航,  Navigation
url: http://xuebage.qh51.com/
established_at: "2016-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
